apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prowjobs-extension
  labels:
    rbac.authorization.k8s.io/aggregate-to-dashboard: "true"
rules:
  - apiGroups:
      - prow.k8s.io
    resources:
      - prowjobs
    verbs:
      - get
      - list
      - watch
